name: personal_portfolio
description: "Kishore's Portfolio Website"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animated_flip_counter: ^0.3.4
  auto_size_text: ^3.0.0
  delightful_toast: ^1.1.0
  entry: ^1.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  logger: ^2.4.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  url_strategy: ^0.2.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
          
    